# Generated by Django 2.2 on 2019-05-01 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190501_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='exchange rate'),
        ),
    ]
