# Generated by Django 2.2.1 on 2019-05-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currency_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Currency'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=2, verbose_name='code')),
                ('alpha3', models.CharField(max_length=3, verbose_name='aplha3')),
                ('flag_emoji', models.CharField(max_length=200, verbose_name='flag emoji')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('currencies', models.ManyToManyField(related_name='countries', to='core.Currency')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
    ]
