# Generated by Django 2.2.1 on 2019-05-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190503_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Currency'),
        ),
    ]
