# Generated by Django 2.2.1 on 2019-05-07 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190505_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.Currency'),
        ),
    ]
