# Generated by Django 2.2.1 on 2019-05-07 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20190505_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='tripuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('collaborator', 'Collaborator')], default='owner', max_length=100, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='tripuser',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_user', to='trip.Trip'),
        ),
        migrations.AlterField(
            model_name='tripuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
