# Generated by Django 2.2.1 on 2019-07-23 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trip.Trip'),
        ),
    ]
