# Generated by Django 2.2.6 on 2019-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20190928_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcategory',
            name='color',
            field=models.CharField(max_length=255, null=True, verbose_name='color'),
        ),
    ]
